### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by staticfloat** [JuliaPackaging/PkgServerLogAnalysis.jl#3]
We should have a CI job that runs the analysis passes on the anonymized data testset, to ensure that it can run without erroring.

**Comment by staticfloat** [comment]
Fixed by #4

**Comment by gguyza001** [comment]
![Uploading AC61B718-5BF7-4A9D-B58D-A5AFF0D549EC.png…]()

**Comment by gguyza001** [comment]
@gguyza001

**Comment by gguyza001** [comment]
หากคุณมีคำถามใดๆเกี่ยวกับตัวเองหรือเว็บไซต์ฉันโปรดส่งอีเมลฉัน

**Comment by gguyza001** [comment]
Ok

**Comment by gguyza001** [comment]
> เราควรมีงาน CI ที่รันการวิเคราะห์ผ่านชุดทดสอบข้อมูลที่ไม่ระบุตัวตนเพื่อให้แน่ใจว่าสามารถทำงานได้โดยไม่มีข้อผิดพลาด
โดยการใช้พัฒนาการของwave

**Comment by gguyza001** [comment]
👋
